// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlhvashqbfvmqfpnuzyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsaHZhc2hxYmZ2bXFmcG51enlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODQ3MzUsImV4cCI6MjA2Mzc2MDczNX0.41L0KUnTOJJW570ivAat31LYNSMoqi6FOuJL8v-9VJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);